config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :materials

  namespace :api do
    jsonapi_resources :materials
    jsonapi_resources :organizations
    jsonapi_resources :offers
    jsonapi_resources :economic_processes
  end

end

app/models/agent.rb
class Agent
  include Mongoid::Document
  
  field :url, type: String
end

app/models/economic_process.rb
class EconomicProcess
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :name, :type => String
  field :uri, :type => String
  field :level, :type => Integer

  include Mongoid::Timestamps
end

app/models/economic_resource.rb
module OpenResources
  class EconomicResource
    include Tripod::Resource

    rdf_type 'http://openresources.io/economic_resource'
    graph_uri 'http://openresources.io/graph'

    # field :name, 'https://schema.org/name'
    field :label, RDF::RDFS.label
    field :description, 'http://purl.org/dc/terms/description'
    field :wikidata_id, 'http://www.wikidata.org/ontology#Item'
  end
end

app/models/economic_resource_type.rb
module OpenResources
  class EconomicResourceType
    include Tripod::Resource

    rdf_type 'http://openresources.io/economic_resource_type'
    graph_uri 'http://openresources.io/graph'

    # field :name, 'https://schema.org/name'
    field :label, RDF::RDFS.label
    field :description, 'http://purl.org/dc/terms/description'
    field :wikidata_id, 'http://www.wikidata.org/ontology#Item'
  end
end

app/models/material.rb
class Material
  include Mongoid::Document

  field :name, type: String
  field :path, type: String
  field :description, type: String
  field :wikidata_id, type: String
  field :wrap_category, type: String
  field :material_stream, type: String
  field :osm_tag, type: String
  field :guidelines, type: String

  include Mongoid::Timestamps # adds created_at and updated_at fields
end

app/models/offer.rb
class Offer
  include Mongoid::Document

  belongs_to :organization
  belongs_to :economic_process, inverse_of: nil
  has_and_belongs_to_many :materials, inverse_of: nil

  include Mongoid::Timestamps
end

app/models/open_resources/process.rb
module OpenResources
  class Process
    include Mongoid::Document
    include Mongoid::Timestamps # adds created_at and updated_at fields

    # field <name>, :type => <type>, :default => <value>
    field :name, :type => String
    field :uri, :type => String

    # has_many :offers

    # You can define indexes on documents using the index macro:
    # index :field <, :unique => true>

    # You can create a composite key in mongoid to replace the default id using the key macro:
    # key :field <, :another_field, :one_more ....>
  end
end

app/models/organization.rb
class Organization
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :name, :type => String
  field :type, :type => String
  field :website, :type => String
  field :description, :type => String

  include Mongoid::Timestamps

  has_many :offers
end

app/models/place.rb
class Place
  include Mongoid::Document
  
  field :name, type: String
  field :latitude, type: Float
  field :longitude, type: Float
  
  # validates :latitude, :longitude, :format => { :with => %r([0-9]+\.[0-9]*) }, :if => Proc.new {|p| (p.latitude.present? && p.longitude.present?) }

end

app/models/recycling_site.rb
module OpenResources
  class RecyclingSite
    include Tripod::Resource

    rdf_type 'http://openresources.io/bringpoint'
    graph_uri 'http://openresources.io/graph'

    field :materials_accepted, 'http://openresources.io/def/material', :multivalued => true
  end
end

app/models/resource.rb
class Resource
  include Mongoid::Document
  include Mongoid::Timestamps # adds created_at and updated_at fields

  # field <name>, :type => <type>, :default => <value>
  field :name, :type => String
  field :url, :type => String

  has_and_belongs_to_many :materials

  # You can define indexes on documents using the index macro:
  # index :field <, :unique => true>

  # You can create a composite key in mongoid to replace the default id using the key macro:
  # key :field <, :another_field, :one_more ....>
end

app/models/stage.rb
class Stage
  include Mongoid::Document
  
  field :name, type: String
  field :description, type: String
  field :weight, type: String

end

app/controllers/api/material_controller.rb
module Api
  class MaterialController < JSONAPI::ResourceController
  end
end

app/controllers/api/materials_controller.rb
module Api
  class MaterialsController < JSONAPI::ResourceController
  end
end

app/controllers/api/offers_controller.rb
module Api
  class OffersController < JSONAPI::ResourceController
  end
end

app/controllers/api/organizations_controller.rb
module Api
  class OrganizationsController < JSONAPI::ResourceController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  def index
    @materials = Material.all
  end

  # GET /materials/1
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  def create
    @material = Material.new(material_params)

    if @material.save
      redirect_to @material, notice: 'Material was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /materials/1
  def update
    if @material.update(material_params)
      redirect_to @material, notice: 'Material was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /materials/1
  def destroy
    @material.destroy
    redirect_to materials_url, notice: 'Material was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def material_params
      params.require(:material).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body

    = yield

app/views/materials/_form.html.haml
= form_for(@material) do |f|
  - if @material.errors.any?
    #error_explanation
      %h2
        = pluralize(@material.errors.count, "error")
        prohibited this material from being saved:
      %ul
        - @material.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/materials/edit.html.haml
%h1 Editing Material
= render 'form'
= link_to 'Show', @material
|
= link_to 'Back', materials_path

app/views/materials/index.html.haml
%p#notice= notice

%h1 Materials

- @materials.each do |material|
  %span= material.name



%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @materials.each do |material|
      %tr
        %td= material.name
        %td= link_to 'Show', material
        %td= link_to 'Edit', edit_material_path(material)
        %td= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Material', new_material_path

app/views/materials/new.html.haml
%h1 New Material
= render 'form'
= link_to 'Back', materials_path

app/views/materials/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @material.name
= link_to 'Edit', edit_material_path(@material)
|
= link_to 'Back', materials_path